version: '2.4'
services:
  api:
    container_name: form3
    image: pedrogutierrez/form3
    ports:
      - "8080:8080"
    entrypoint:
      - form3
      - --repo=postgres
      - --repo-uri=postgresql://form3:form3@postgres:5432/form3?sslmode=disable
      - --repo-migrations=/etc/form3/schema
      - --metrics=true
      - --admin=true
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "form3"
      POSTGRES_PASSWORD: "form3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U form3"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/pg/data:/var/lib/postgresql/data
      - ./data/pg/run:/var/run/postgresql
      - ./data/pg/init:/docker-entrypoint-initdb.d
